### ISSUE TITLE
Failed to run on linux (No such file or directory)

### ISSUE THREAD

**Issue by juozaspo** [qarmin/Win32Fuzzer#1]
Trying to run on Linux results in error.
```
$ cargo run --release
   Compiling same-file v1.0.6
   Compiling walkdir v2.3.2
   Compiling win32_fuzzer v1.0.0 (/home/juozas/Win32Fuzzer)
    Finished release [optimized] target(s) in 25.69s
     Running `target/release/win32_fuzzer`
thread 'main' panicked at 'Failed to open /home/rafal/test/windows-rs/crates/libs/sys/src/Windows/Win32/Graphics/Printing/mod.rs, due Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/parse_file.rs:7:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It references a path on non-existing location.

**Comment by steawth** [comment]
The WINDOWS_RS_FOLDER is statically assigned in the settings.rs file. Try updating it to point to your local install instead the one specified in the git repo.
https://github.com/qarmin/Win32Fuzzer/blob/9f287f7e6277103f63ee97c715a5d7ce3a46288f/src/settings.rs#L4

**Comment by qarmin** [comment]
In https://github.com/qarmin/Win32Fuzzer/commit/172d4d19f10cd6015801cbf52467dcda05c8d663 I added method to setup own path to `windows-rs` just by typing `cargo run /home/path/to/windows-rs`
